---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: curl,gnupg
    state: present

- name: Add Tailscale GPG key
  apt_key:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.asc
    state: present

- name: Add Tailscale repository
  apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/debian bookworm main"
    state: present

- name: Update apt cache after adding Tailscale repository
  apt:
    update_cache: yes

- name: Install Tailscale
  apt:
    name: tailscale
    state: present

- name: Start and enable Tailscale service
  systemd:
    name: tailscaled
    enabled: yes
    state: started

- name: Write IP forwarding configuration to 99-tailscale.conf
  copy:
    dest: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.forwarding=1

- name: Apply sysctl settings
  command: sysctl -p /etc/sysctl.d/99-tailscale.conf
