- name: Update packages on Debian-based systems
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update packages on Arch Linux
  command: pacman -Syu --noconfirm
  when: ansible_os_family == "Archlinux"

- name: Set system timezone
  ansible.builtin.timezone:
    name: Asia/Shanghai

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install basic packages
  package:
    name:
      - vim
      - tmux
      - zsh
      - fzf
      - zoxide
      - exa
      - git
      - wget
      - man
    state: present
