- name: Cloud install
  hosts: all
  become: yes

  roles:
    - role: debinit
      when: ansible_facts['os_family'] == "Debian"

    - role: archinit
      when: ansible_facts['os_family'] == "Archlinux"

    - role: basic
