---
- name: Update Debian systems
  hosts: debian
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
        autoremove: yes
        autoclean: yes
