---
- name: Ensure Python and nginx are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-flask
    - python3-gunicorn
    - nginx

- name: Create systemd service for Gunicorn
  template:
    src: webserver.service.j2
    dest: /etc/systemd/system/webserver.service

- name: Start and enable Gunicorn service
  systemd:
    name: webserver
    enabled: yes
    state: started

- name: Configure Nginx to proxy requests to Gunicorn
  template:
    src: webserver.j2
    dest: /etc/nginx/sites-available/webserver

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/webserver
    dest: /etc/nginx/sites-enabled/myapp
    state: link

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test Nginx configuration
  command: nginx -t

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

